### ISSUE TITLE
Gizmo emissive material too faint

### ISSUE THREAD

**Issue by Andargor** [xyahh/UE4RuntimeTransformer#4]
Hello, and thanks for your work.

I tried out the plugin, and on my level the gizmos appeared black. I made another set of materials for the gizmos with a multiplier of 1000 on the emissive color parameter, derived the gizmos and assigned the new materials to all the components. This made the gizmos have color again.

Could you add a parameter that would apply a multiplier to the emissive color, to avoid having to derive and assign materials this way depending on level lighting? It would make implementation much easier.

**Comment by xyahh** [comment]
The material part was made in seconds hehe because ot is not really part of the plugin "purpose" but rather just some sample things to start with. 
Thank you for your suggestion and will double check on the materials once again !
