### ISSUE TITLE
IgnoreNonReplicatedObjects filter may filter out the wrong array indices.

### ISSUE THREAD

**Issue by HiIAmMoot** [xyahh/UE4RuntimeTransformer#5]
https://github.com/xyahh/UE4RuntimeTransformer/blob/462df38f56ae7f7c004072dbbabd9e68312e2d64/RuntimeTransformer/Source/RuntimeTransformer/Private/TransformerPawn.cpp#L130

Using the above code as context, the moment outHits.RemoveAt(i) is triggered, the array will shrink and thus will not be the same length as checkHits. Meaning that the next time this line of code is called, it will remove the wrong index because the indices shifted.

**Comment by xyahh** [comment]
You are completely right! I should be using the Iterators for that!

**Comment by xyahh** [comment]
Thanks for the heads up ;)
