### ISSUE TITLE
MacOSX version?

### ISSUE THREAD

**Issue by Noelok** [xyahh/UE4RuntimeTransformer#6]
Hi Xyahh!
I'm very interested in your plugin, it's exactly what I'm looking for!
Do you have a mac version of it? 
Thank you!
Noel.

**Comment by xyahh** [comment]
Hi Noel!
Yes I would like to have the plugin also available for Mac (people have asked for it).
But I have not been able to get hands on a Mac lately... 
I need a Mac to compile the code and check if it all works before sending it to Epic Games Marketplace and claim it's working!
Trust me that as soon as I get hands on a Mac, the first thing I will do is test my plugin there!

**Comment by xyahh** [comment]
After Several Requests I finally managed to get a Mac and change some code so that it compiles properly as well as whitelisting the Mac OS for the Plugin.
This new version of the plugin should be working for the Mac (4.26 only for now!)
